import { angularLanguage } from "@codemirror/lang-angular";
import { cppLanguage } from "@codemirror/lang-cpp";
import { cssLanguage } from "@codemirror/lang-css";
import { goLanguage } from "@codemirror/lang-go";
import { htmlLanguage } from "@codemirror/lang-html";
import { javaLanguage } from "@codemirror/lang-java";
import { javascriptLanguage, jsxLanguage, tsxLanguage, typescriptLanguage } from "@codemirror/lang-javascript";
import { jinjaLanguage } from "@codemirror/lang-jinja";
import { jsonLanguage } from "@codemirror/lang-json";
import { lessLanguage } from "@codemirror/lang-less";
import { liquidLanguage } from "@codemirror/lang-liquid";
import { markdownLanguage } from "@codemirror/lang-markdown";
import { phpLanguage } from "@codemirror/lang-php";
import { pythonLanguage } from "@codemirror/lang-python";
import { rustLanguage } from "@codemirror/lang-rust";
import { sassLanguage } from "@codemirror/lang-sass";
import { sql } from "@codemirror/lang-sql";
import { vueLanguage } from "@codemirror/lang-vue";
import { wastLanguage } from "@codemirror/lang-wast";
import { xmlLanguage } from "@codemirror/lang-xml";
import { yamlLanguage } from "@codemirror/lang-yaml";
import { svelteLanguage } from "@replit/codemirror-lang-svelte";
import type { LanguageConfig } from "./types";

type PrismSupportedLanguage = {
  id: string;
  aliases?: string[];
};

const PRISM_SUPPORTED_LANGUAGES: PrismSupportedLanguage[] = [
  { id: "markup", aliases: ["html", "xml", "svg", "mathml", "ssml", "atom", "rss"] },
  { id: "css" },
  { id: "clike" },
  { id: "javascript", aliases: ["js"] },
  { id: "abap" },
  { id: "abnf" },
  { id: "actionscript" },
  { id: "ada" },
  { id: "agda" },
  { id: "al" },
  { id: "antlr4", aliases: ["g4"] },
  { id: "apacheconf" },
  { id: "apex" },
  { id: "apl" },
  { id: "applescript" },
  { id: "aql" },
  { id: "arduino", aliases: ["ino"] },
  { id: "arff" },
  { id: "armasm", aliases: ["arm-asm"] },
  { id: "arturo", aliases: ["art"] },
  { id: "asciidoc", aliases: ["adoc"] },
  { id: "aspnet" },
  { id: "asm6502" },
  { id: "asmatmel" },
  { id: "autohotkey" },
  { id: "autoit" },
  { id: "avisynth", aliases: ["avs"] },
  { id: "avro-idl", aliases: ["avdl"] },
  { id: "awk", aliases: ["gawk"] },
  { id: "bash", aliases: ["sh", "shell"] },
  { id: "basic" },
  { id: "batch" },
  { id: "bbcode", aliases: ["shortcode"] },
  { id: "bbj" },
  { id: "bicep" },
  { id: "birb" },
  { id: "bison" },
  { id: "bnf", aliases: ["rbnf"] },
  { id: "bqn" },
  { id: "brainfuck" },
  { id: "brightscript" },
  { id: "bro" },
  { id: "bsl", aliases: ["oscript"] },
  { id: "c" },
  { id: "csharp", aliases: ["cs", "dotnet"] },
  { id: "cpp" },
  { id: "cfscript", aliases: ["cfc"] },
  { id: "chaiscript" },
  { id: "cil" },
  { id: "cilkc", aliases: ["cilk-c"] },
  { id: "cilkcpp", aliases: ["cilk-cpp", "cilk"] },
  { id: "clojure" },
  { id: "cmake" },
  { id: "cobol" },
  { id: "coffeescript", aliases: ["coffee"] },
  { id: "concurnas", aliases: ["conc"] },
  { id: "csp" },
  { id: "cooklang" },
  { id: "coq" },
  { id: "crystal" },
  { id: "css-extras" },
  { id: "csv" },
  { id: "cue" },
  { id: "cypher" },
  { id: "d" },
  { id: "dart" },
  { id: "dataweave" },
  { id: "dax" },
  { id: "dhall" },
  { id: "diff" },
  { id: "django", aliases: ["jinja2"] },
  { id: "dns-zone-file", aliases: ["dns-zone"] },
  { id: "docker", aliases: ["dockerfile"] },
  { id: "dot", aliases: ["gv"] },
  { id: "ebnf" },
  { id: "editorconfig" },
  { id: "eiffel" },
  { id: "ejs", aliases: ["eta"] },
  { id: "elixir" },
  { id: "elm" },
  { id: "etlua" },
  { id: "erb" },
  { id: "erlang" },
  { id: "excel-formula", aliases: ["xlsx", "xls"] },
  { id: "fsharp" },
  { id: "factor" },
  { id: "false" },
  { id: "firestore-security-rules" },
  { id: "flow" },
  { id: "fortran" },
  { id: "ftl" },
  { id: "gml", aliases: ["gamemakerlanguage"] },
  { id: "gap" },
  { id: "gcode" },
  { id: "gdscript" },
  { id: "gedcom" },
  { id: "gettext", aliases: ["po"] },
  { id: "gherkin" },
  { id: "git" },
  { id: "glsl" },
  { id: "gn", aliases: ["gni"] },
  { id: "linker-script", aliases: ["ld"] },
  { id: "go" },
  { id: "go-module", aliases: ["go-mod"] },
  { id: "gradle" },
  { id: "graphql" },
  { id: "groovy" },
  { id: "haml" },
  { id: "handlebars", aliases: ["hbs", "mustache"] },
  { id: "haskell", aliases: ["hs"] },
  { id: "haxe" },
  { id: "hcl" },
  { id: "hlsl" },
  { id: "hoon" },
  { id: "http" },
  { id: "hpkp" },
  { id: "hsts" },
  { id: "ichigojam" },
  { id: "icon" },
  { id: "icu-message-format" },
  { id: "idris", aliases: ["idr"] },
  { id: "ignore", aliases: ["gitignore", "hgignore", "npmignore"] },
  { id: "inform7" },
  { id: "ini" },
  { id: "io" },
  { id: "j" },
  { id: "java" },
  { id: "javadoc" },
  { id: "javadoclike" },
  { id: "javastacktrace" },
  { id: "jexl" },
  { id: "jolie" },
  { id: "jq" },
  { id: "jsdoc" },
  { id: "js-extras" },
  { id: "json", aliases: ["webmanifest"] },
  { id: "json5" },
  { id: "jsonp" },
  { id: "jsstacktrace" },
  { id: "js-templates" },
  { id: "julia" },
  { id: "keepalived" },
  { id: "keyman" },
  { id: "kotlin", aliases: ["kt", "kts"] },
  { id: "kumir", aliases: ["kum"] },
  { id: "kusto" },
  { id: "latex", aliases: ["tex", "context"] },
  { id: "latte" },
  { id: "less" },
  { id: "lilypond", aliases: ["ly"] },
  { id: "liquid" },
  { id: "lisp", aliases: ["emacs", "elisp", "emacs-lisp"] },
  { id: "livescript" },
  { id: "llvm" },
  { id: "log" },
  { id: "lolcode" },
  { id: "lua" },
  { id: "magma" },
  { id: "makefile" },
  { id: "markdown", aliases: ["md"] },
  { id: "markup-templating" },
  { id: "mata" },
  { id: "matlab" },
  { id: "maxscript" },
  { id: "mel" },
  { id: "mermaid" },
  { id: "metafont" },
  { id: "mizar" },
  { id: "mongodb" },
  { id: "monkey" },
  { id: "moonscript", aliases: ["moon"] },
  { id: "n1ql" },
  { id: "n4js", aliases: ["n4jsd"] },
  { id: "nand2tetris-hdl" },
  { id: "naniscript", aliases: ["nani"] },
  { id: "nasm" },
  { id: "neon" },
  { id: "nevod" },
  { id: "nginx" },
  { id: "nim" },
  { id: "nix" },
  { id: "nsis" },
  { id: "objectivec", aliases: ["objc"] },
  { id: "ocaml" },
  { id: "odin" },
  { id: "opencl" },
  { id: "openqasm", aliases: ["qasm"] },
  { id: "oz" },
  { id: "parigp" },
  { id: "parser" },
  { id: "pascal", aliases: ["objectpascal"] },
  { id: "pascaligo" },
  { id: "psl" },
  { id: "pcaxis", aliases: ["px"] },
  { id: "peoplecode", aliases: ["pcode"] },
  { id: "perl" },
  { id: "php" },
  { id: "phpdoc" },
  { id: "php-extras" },
  { id: "plant-uml", aliases: ["plantuml"] },
  { id: "plsql" },
  { id: "powerquery", aliases: ["pq", "mscript"] },
  { id: "powershell" },
  { id: "processing" },
  { id: "prolog" },
  { id: "promql" },
  { id: "properties" },
  { id: "protobuf" },
  { id: "pug" },
  { id: "puppet" },
  { id: "pure" },
  { id: "purebasic", aliases: ["pbfasm"] },
  { id: "purescript", aliases: ["purs"] },
  { id: "python", aliases: ["py"] },
  { id: "qsharp", aliases: ["qs"] },
  { id: "q" },
  { id: "qml" },
  { id: "qore" },
  { id: "r" },
  { id: "racket", aliases: ["rkt"] },
  { id: "cshtml", aliases: ["razor"] },
  { id: "jsx" },
  { id: "tsx" },
  { id: "reason" },
  { id: "regex" },
  { id: "rego" },
  { id: "renpy", aliases: ["rpy"] },
  { id: "rescript", aliases: ["res"] },
  { id: "rest" },
  { id: "rip" },
  { id: "roboconf" },
  { id: "robotframework", aliases: ["robot"] },
  { id: "ruby", aliases: ["rb"] },
  { id: "rust" },
  { id: "sas" },
  { id: "sass" },
  { id: "scss" },
  { id: "scala" },
  { id: "scheme" },
  { id: "shell-session", aliases: ["sh-session", "shellsession"] },
  { id: "smali" },
  { id: "smalltalk" },
  { id: "smarty" },
  { id: "sml", aliases: ["smlnj"] },
  { id: "solidity", aliases: ["sol"] },
  { id: "solution-file", aliases: ["sln"] },
  { id: "soy" },
  { id: "sparql", aliases: ["rq"] },
  { id: "splunk-spl" },
  { id: "sqf" },
  { id: "sql" },
  { id: "squirrel" },
  { id: "stan" },
  { id: "stata" },
  { id: "iecst" },
  { id: "stylus" },
  { id: "supercollider", aliases: ["sclang"] },
  { id: "swift" },
  { id: "systemd" },
  { id: "t4-templating" },
  { id: "t4-cs", aliases: ["t4"] },
  { id: "t4-vb" },
  { id: "tap" },
  { id: "tcl" },
  { id: "tt2" },
  { id: "textile" },
  { id: "toml" },
  { id: "tremor", aliases: ["trickle", "troy"] },
  { id: "turtle", aliases: ["trig"] },
  { id: "twig" },
  { id: "typescript", aliases: ["ts"] },
  { id: "typoscript", aliases: ["tsconfig"] },
  { id: "unrealscript", aliases: ["uscript", "uc"] },
  { id: "uorazor" },
  { id: "uri", aliases: ["url"] },
  { id: "v" },
  { id: "vala" },
  { id: "vbnet" },
  { id: "velocity" },
  { id: "verilog" },
  { id: "vhdl" },
  { id: "vim" },
  { id: "visual-basic", aliases: ["vb", "vba"] },
  { id: "warpscript" },
  { id: "wasm" },
  { id: "web-idl", aliases: ["webidl"] },
  { id: "wgsl" },
  { id: "wiki" },
  { id: "wolfram", aliases: ["mathematica", "nb", "wl"] },
  { id: "wren" },
  { id: "xeora", aliases: ["xeoracube"] },
  { id: "xml-doc" },
  { id: "xojo" },
  { id: "xquery" },
  { id: "yaml", aliases: ["yml"] },
  { id: "yang" },
  { id: "zig" }
];

const CODEMIRROR_LANGUAGES: LanguageConfig[] = [
  { id: "angular", aliases: ["ng"], parserLanguage: angularLanguage, preferPrism: true },
  { id: "css", parserLanguage: cssLanguage, preferPrism: true },
  { id: "cpp", aliases: ["c++","cxx","cc","hpp","h++"], parserLanguage: cppLanguage, preferPrism: true },
  { id: "go", parserLanguage: goLanguage, preferPrism: true },
  { id: "html", aliases: ["htm"], parserLanguage: htmlLanguage, preferPrism: true },
  { id: "java", parserLanguage: javaLanguage, preferPrism: true },
  { id: "javascript", aliases: ["js","mjs","cjs"], parserLanguage: javascriptLanguage, preferPrism: true },
  { id: "typescript", aliases: ["ts"], parserLanguage: typescriptLanguage, preferPrism: true },
  { id: "jsx", parserLanguage: jsxLanguage, preferPrism: true },
  { id: "tsx", parserLanguage: tsxLanguage, preferPrism: true },
  { id: "jinja", aliases: ["jinja2","django"], parserLanguage: jinjaLanguage, preferPrism: true },
  { id: "json", aliases: ["webmanifest"], parserLanguage: jsonLanguage, preferPrism: true },
  { id: "less", parserLanguage: lessLanguage, preferPrism: true },
  { id: "liquid", aliases: ["shopify"], parserLanguage: liquidLanguage, preferPrism: true },
  { id: "markdown", aliases: ["md"], parserLanguage: markdownLanguage, preferPrism: true },
  { id: "php", parserLanguage: phpLanguage, preferPrism: true },
  { id: "python", aliases: ["py"], parserLanguage: pythonLanguage, preferPrism: true },
  { id: "rust", aliases: ["rs"], parserLanguage: rustLanguage, preferPrism: true },
  { id: "sass", aliases: ["scss"], parserLanguage: sassLanguage, preferPrism: true },
  { id: "sql", parserLanguage: sql().language, preferPrism: true },
  { id: "vue", parserLanguage: vueLanguage, preferPrism: true },
  { id: "wasm", aliases: ["wat","wast","webassembly"], parserLanguage: wastLanguage, preferPrism: true },
  { id: "xml", aliases: ["xsd"], parserLanguage: xmlLanguage, preferPrism: true },
  { id: "yaml", aliases: ["yml"], parserLanguage: yamlLanguage, preferPrism: true },
  { id: "svelte", aliases: ["sv"], parserLanguage: svelteLanguage, preferPrism: true },
];

const CODEMIRROR_BUILT_IN_LANGUAGES = CODEMIRROR_LANGUAGES;
const CODEMIRROR_LANGUAGE_IDS = new Set(CODEMIRROR_BUILT_IN_LANGUAGES.flatMap(getLanguageIds).map((id) => id.toLowerCase()));

const PRISM_BUILT_IN_LANGUAGES: LanguageConfig[] = PRISM_SUPPORTED_LANGUAGES.flatMap((language) => {
  const ids = getLanguageIds(language).filter((id) => !CODEMIRROR_LANGUAGE_IDS.has(id.toLowerCase()));
  if (ids.length === 0) {
    return [];
  }
  const [id, ...aliases] = ids;
  return [{
    id,
    aliases: aliases.length > 0 ? aliases : undefined,
    preferPrism: true
  }];
});

export const BUILT_IN_LANGUAGES: LanguageConfig[] = [
  ...CODEMIRROR_BUILT_IN_LANGUAGES,
  ...PRISM_BUILT_IN_LANGUAGES
];

function getLanguageIds(language: PrismSupportedLanguage | LanguageConfig): string[] {
  return [language.id, ...(language.aliases ?? [])];
}
